# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='city',
        ),
    ]
